scan:
  image: registry.gitlab.com/eawalden/py-mi-ps/sonar-scanner:latest
  script:
    - sonar-scanner -Dsonar.projectKey=$PROJ_KEY -Dsonar.organization=$ORGANIZATION -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$LOGIN_KEY -Dsonar.branch.name=this/test -Dsonar.projectVersion=1.0
